server:
  port: 8595
spring:
  datasource:
    url: jdbc:mysql://localhost/employeeDB?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:7878/oauth/check_token
    client:
      client-id: web
      client-secret: webpass